version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3


workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 090146717911.dkr.ecr.ca-central-1.amazonaws.com"
          tag: "${CIRCLE_SHA1}"
