version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0


workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image: # orb built-in job
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          tag: '${CIRCLE_SHA1}'  
 #     - aws-ecs/deploy-service-update: # orb built-in job 
 #         requires:
 #           - aws-ecr/build-and-push-image
 #         family: '${MY_APP_PREFIX}-service'
 #         cluster: '${MY_APP_PREFIX}-cluster'
 #         container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
